import { ChecklistItem } from "@/types";

export const autoClaimChecklist: ChecklistItem[] = [
  // Vehicle Damage Photos
  {
    id: "photo-front",
    label: "Front of vehicle",
    description: "Full front view showing bumper, hood, headlights, and grille",
    completed: false,
    category: "vehicle_damage",
    required: true,
  },
  {
    id: "photo-rear",
    label: "Rear of vehicle",
    description: "Full rear view showing bumper, trunk/tailgate, taillights",
    completed: false,
    category: "vehicle_damage",
    required: true,
  },
  {
    id: "photo-left",
    label: "Left side of vehicle",
    description: "Full driver's side view from front to rear",
    completed: false,
    category: "vehicle_damage",
    required: true,
  },
  {
    id: "photo-right",
    label: "Right side of vehicle",
    description: "Full passenger's side view from front to rear",
    completed: false,
    category: "vehicle_damage",
    required: true,
  },
  {
    id: "photo-damage-close-1",
    label: "Close-up of primary damage",
    description: "Detailed close-up of the main damage area",
    completed: false,
    category: "vehicle_damage",
    required: true,
  },
  {
    id: "photo-damage-close-2",
    label: "Close-up of secondary damage",
    description: "Detailed close-up of any additional damage areas",
    completed: false,
    category: "vehicle_damage",
    required: true,
  },
  {
    id: "photo-vin",
    label: "VIN plate",
    description: "Vehicle Identification Number plate (usually on dashboard, driver's side)",
    completed: false,
    category: "vehicle_damage",
    required: true,
  },
  {
    id: "photo-odometer",
    label: "Odometer reading",
    description: "Current mileage displayed on the odometer",
    completed: false,
    category: "vehicle_damage",
    required: true,
  },
  {
    id: "photo-license",
    label: "License plate",
    description: "Clear photo of your license plate",
    completed: false,
    category: "vehicle_damage",
    required: true,
  },
  {
    id: "photo-interior",
    label: "Interior damage (if any)",
    description: "Photos of any interior damage including deployed airbags",
    completed: false,
    category: "vehicle_damage",
    required: false,
  },
  {
    id: "photo-underbody",
    label: "Underbody damage (if visible)",
    description: "Any visible damage to undercarriage or frame",
    completed: false,
    category: "vehicle_damage",
    required: false,
  },
  {
    id: "photo-pre-existing",
    label: "Pre-existing damage documentation",
    description: "Photos clearly showing any pre-existing damage separate from the accident",
    completed: false,
    category: "vehicle_damage",
    required: false,
  },
  // Accident Scene
  {
    id: "scene-overview",
    label: "Accident scene overview",
    description: "Wide shot showing the accident location, road layout, and surroundings",
    completed: false,
    category: "accident_scene",
    required: true,
  },
  {
    id: "scene-road",
    label: "Road conditions",
    description: "Photos showing road surface, any potholes, wet conditions, or debris",
    completed: false,
    category: "accident_scene",
    required: true,
  },
  {
    id: "scene-signs",
    label: "Traffic signs and signals",
    description: "All relevant traffic signs, signals, and road markings near the scene",
    completed: false,
    category: "accident_scene",
    required: true,
  },
  {
    id: "scene-skid",
    label: "Skid marks or debris",
    description: "Any skid marks, tire tracks, or debris on the road",
    completed: false,
    category: "accident_scene",
    required: false,
  },
  {
    id: "scene-cameras",
    label: "Nearby surveillance cameras",
    description: "Note and photograph any nearby security or traffic cameras",
    completed: false,
    category: "accident_scene",
    required: false,
  },
  // Third-party info
  {
    id: "other-driver-info",
    label: "Other driver's information",
    description: "Name, phone, insurance company, policy number, license plate, driver's license",
    completed: false,
    category: "other",
    required: true,
  },
  {
    id: "witness-info",
    label: "Witness contact information",
    description: "Names and phone numbers of any witnesses",
    completed: false,
    category: "other",
    required: false,
  },
  {
    id: "police-report",
    label: "Police report number",
    description: "Report number and responding officer information",
    completed: false,
    category: "police_report",
    required: true,
  },
];
