import type { Metadata } from "next";
import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "ClaimCoach terms of service. Read about the terms and conditions governing your use of ClaimCoach.",
  alternates: { canonical: "/terms" },
};

export default function TermsPage() {
  return (
    <div className="flex flex-col min-h-screen bg-panel">
      <Header />

      <main className="flex-1">
        <div className="container-narrow py-16 sm:py-20">
          <p className="text-caption uppercase tracking-[0.2em] text-black/60 font-medium mb-3">
            Legal
          </p>
          <h1 className="text-display-sm sm:text-display text-black mb-10">
            Terms of Service
          </h1>

          <div className="prose-container space-y-8 text-body text-[#4a555e] leading-relaxed">
            <p className="text-body-sm text-[#4a555e]/60">
              Last updated: February 14, 2026
            </p>

            <section>
              <h2 className="text-heading text-black font-semibold mb-3">
                1. Acceptance of Terms
              </h2>
              <p>
                By accessing or using ClaimCoach (&quot;the Service&quot;), you
                agree to be bound by these Terms of Service. If you do not agree,
                do not use the Service.
              </p>
            </section>

            <section>
              <h2 className="text-heading text-black font-semibold mb-3">
                2. Description of Service
              </h2>
              <p>
                ClaimCoach is an AI-powered educational tool that helps consumers
                understand and evaluate insurance claim settlement offers. The
                Service provides analysis, document generation, and informational
                resources to help you negotiate with your insurance company.
              </p>
            </section>

            <section>
              <h2 className="text-heading text-black font-semibold mb-3">
                3. Not Legal Advice
              </h2>
              <div className="bg-coral/5 border border-coral/20 p-4">
                <p className="font-semibold text-black mb-2">
                  Important Disclaimer
                </p>
                <p>
                  ClaimCoach is an educational and informational tool.{" "}
                  <strong className="text-black">
                    It does not provide legal, financial, or insurance advice.
                  </strong>{" "}
                  The information, analysis, and documents generated by our
                  Service are for educational purposes only. You should consult
                  with a licensed attorney or public adjuster for advice specific
                  to your situation. We do not guarantee any particular outcome
                  for your insurance claim.
                </p>
              </div>
            </section>

            <section>
              <h2 className="text-heading text-black font-semibold mb-3">
                4. User Accounts
              </h2>
              <ul className="list-disc pl-5 space-y-2">
                <li>
                  You must provide accurate and complete information when
                  creating an account.
                </li>
                <li>
                  You are responsible for maintaining the security of your
                  account credentials.
                </li>
                <li>
                  You must be at least 18 years old to use the Service.
                </li>
                <li>
                  One account per person. Accounts are non-transferable.
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-heading text-black font-semibold mb-3">
                5. Payments and Refunds
              </h2>
              <ul className="list-disc pl-5 space-y-2">
                <li>
                  <strong className="text-black">Free tier:</strong> Basic claim
                  analysis at no cost, no credit card required.
                </li>
                <li>
                  <strong className="text-black">Per-claim payment:</strong>{" "}
                  One-time payment of $79 per claim for the full toolkit. No
                  recurring charges.
                </li>
                <li>
                  <strong className="text-black">Pro subscription:</strong>{" "}
                  $147/quarter ($49/month equivalent) for unlimited claims.
                  Cancel anytime.
                </li>
                <li>
                  <strong className="text-black">30-day guarantee:</strong> If
                  you&apos;re not satisfied, contact us within 30 days for a full
                  refund.
                </li>
              </ul>
              <p className="mt-3">
                All payments are processed securely by Stripe. Prices are in US
                dollars and may be updated with advance notice.
              </p>
            </section>

            <section>
              <h2 className="text-heading text-black font-semibold mb-3">
                6. Acceptable Use
              </h2>
              <p>You agree not to:</p>
              <ul className="list-disc pl-5 mt-3 space-y-2">
                <li>
                  Use the Service for any unlawful purpose or to submit
                  fraudulent claims.
                </li>
                <li>
                  Upload documents containing information about other
                  people&apos;s claims without their consent.
                </li>
                <li>
                  Attempt to reverse-engineer, decompile, or extract our AI
                  models or proprietary algorithms.
                </li>
                <li>
                  Use automated tools to scrape, crawl, or bulk-access the
                  Service.
                </li>
                <li>
                  Resell or redistribute the output of the Service without
                  permission.
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-heading text-black font-semibold mb-3">
                7. Intellectual Property
              </h2>
              <p>
                The Service, including its design, code, AI models, and content,
                is owned by ClaimCoach and protected by intellectual property
                laws. Documents generated for your claims (counter-offer letters,
                reports, etc.) are yours to use for your personal insurance
                negotiations.
              </p>
            </section>

            <section>
              <h2 className="text-heading text-black font-semibold mb-3">
                8. AI-Generated Content
              </h2>
              <p>
                Our Service uses artificial intelligence to analyze documents and
                generate content. While we strive for accuracy, AI-generated
                content may contain errors or omissions. You are responsible for
                reviewing all generated content before submitting it to your
                insurance company. ClaimCoach is not liable for any inaccuracies
                in AI-generated analysis or documents.
              </p>
            </section>

            <section>
              <h2 className="text-heading text-black font-semibold mb-3">
                9. Limitation of Liability
              </h2>
              <p>
                To the maximum extent permitted by law, ClaimCoach shall not be
                liable for any indirect, incidental, special, consequential, or
                punitive damages, including loss of profits, data, or other
                intangible losses resulting from your use of the Service. Our
                total liability shall not exceed the amount you paid for the
                Service in the 12 months preceding the claim.
              </p>
            </section>

            <section>
              <h2 className="text-heading text-black font-semibold mb-3">
                10. Termination
              </h2>
              <p>
                We may suspend or terminate your account if you violate these
                Terms. You may delete your account at any time. Upon
                termination, your right to use the Service ceases immediately,
                and we may delete your data in accordance with our Privacy
                Policy.
              </p>
            </section>

            <section>
              <h2 className="text-heading text-black font-semibold mb-3">
                11. Changes to Terms
              </h2>
              <p>
                We may update these Terms from time to time. We will notify you
                of material changes by posting the updated Terms on this page.
                Continued use of the Service after changes constitutes
                acceptance of the new Terms.
              </p>
            </section>

            <section>
              <h2 className="text-heading text-black font-semibold mb-3">
                12. Governing Law
              </h2>
              <p>
                These Terms are governed by the laws of the State of Delaware,
                United States, without regard to conflict of law principles.
              </p>
            </section>

            <section>
              <h2 className="text-heading text-black font-semibold mb-3">
                13. Contact
              </h2>
              <p>
                For questions about these Terms, contact us at{" "}
                <a
                  href="mailto:legal@claimcoach.app"
                  className="text-black underline hover:text-coral transition-colors"
                >
                  legal@claimcoach.app
                </a>
                .
              </p>
            </section>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
