import Link from "next/link";
import { CarValueEstimator } from "@/components/tools/car-value-estimator";
import { KeyTakeaway } from "@/components/guides/key-takeaway";
import { CTABox } from "@/components/guides/cta-box";
import { DataTable } from "@/components/guides/data-table";

/* ---------------------------------------------------------------------- */
/*  Headings                                                                */
/* ---------------------------------------------------------------------- */

export const headings = [
  {
    id: "who-creates-your-report",
    text: "Who Creates Your Valuation Report",
    level: 2,
  },
  {
    id: "how-to-request-your-report",
    text: "How to Request Your Report",
    level: 3,
  },
  {
    id: "five-sections-of-a-valuation-report",
    text: "The Five Key Sections of a Valuation Report",
    level: 2,
  },
  {
    id: "vehicle-identification",
    text: "1. Vehicle Identification",
    level: 3,
  },
  {
    id: "condition-rating",
    text: "2. Condition Rating",
    level: 3,
  },
  {
    id: "comparable-vehicles",
    text: "3. Comparable Vehicles",
    level: 3,
  },
  {
    id: "adjustments",
    text: "4. Adjustments",
    level: 3,
  },
  {
    id: "final-acv",
    text: "5. Final ACV",
    level: 3,
  },
  {
    id: "red-flags-in-comparables",
    text: "Red Flags in the Comparable Vehicles",
    level: 2,
  },
  {
    id: "common-comparable-errors",
    text: "Common Comparable Selection Errors",
    level: 3,
  },
  {
    id: "how-to-dispute-the-report",
    text: "How to Dispute the Valuation Report",
    level: 2,
  },
  {
    id: "check-your-own-value",
    text: "Check Your Own Vehicle&apos;s Value",
    level: 3,
  },
  {
    id: "the-bottom-line",
    text: "The Bottom Line",
    level: 2,
  },
  {
    id: "related-guides",
    text: "Related Guides",
    level: 2,
  },
];

/* ---------------------------------------------------------------------- */
/*  Article                                                                 */
/* ---------------------------------------------------------------------- */

export default function HowToReadValuationReport() {
  return (
    <>
      <p>
        When your insurer declares your car a total loss, the settlement offer
        is not pulled from thin air. It comes from a formal{" "}
        <strong>valuation report</strong> &mdash; a document generated by a
        third-party software platform that lists comparable vehicles, applies
        adjustments for condition and mileage, and produces an estimated
        actual cash value (ACV). You are entitled to a copy of this report,
        and reading it carefully is the single most effective first step in
        evaluating whether your offer is fair. Most errors, omissions, and
        undervaluation issues are visible in the report itself &mdash; if you
        know what to look for.
      </p>

      <CTABox />

      <KeyTakeaway>
        <p>
          Request your full valuation report from your adjuster before
          accepting or rejecting any offer. The report contains the comparables
          and adjustments that produced your ACV. Errors in trim level,
          mileage, condition, and geography are common and directly affect your
          payout.
        </p>
      </KeyTakeaway>

      {/* ---------------------------------------------------------------- */}
      {/*  Who Creates Your Report                                          */}
      {/* ---------------------------------------------------------------- */}

      <h2 id="who-creates-your-report">Who Creates Your Valuation Report</h2>

      <p>
        Most major U.S. insurers do not calculate ACV in-house. They license
        one of three specialized third-party valuation platforms:
      </p>

      <ul>
        <li>
          <strong>CCC Intelligent Solutions (CCC One)</strong> &mdash; the most
          widely used platform in the U.S., used by State Farm, Allstate,
          Farmers, Nationwide, and others
        </li>
        <li>
          <strong>Mitchell International</strong> &mdash; used by GEICO and
          several regional carriers
        </li>
        <li>
          <strong>Audatex (Solera)</strong> &mdash; used by a range of mid-size
          insurers and third-party administrators
        </li>
      </ul>

      <p>
        Each platform uses a comparable-sales methodology: they identify
        recently sold or currently listed vehicles matching yours in your local
        market, then apply adjustments to normalize for differences between
        those vehicles and yours. The result is your estimated ACV.
      </p>

      <p>
        The platforms are tools, not authorities. They are only as accurate as
        the data they pull and the parameters the insurer sets. Errors in
        comparable selection, condition rating, and adjustment factors are
        common &mdash; and they all flow directly into your settlement offer.
      </p>

      <h3 id="how-to-request-your-report">How to Request Your Report</h3>

      <p>
        You have the right to a copy of the valuation report that was used to
        set your settlement offer. In most states, insurers are required to
        provide it upon request. To get yours:
      </p>

      <p>
        Send a written request to your adjuster by email. Use a subject line
        like: &quot;Request for Full Valuation Report &mdash; Claim #[number].&quot;
        State that you are requesting the complete CCC / Mitchell / Audatex
        valuation report including all comparable vehicles and adjustments
        used to calculate the ACV in your settlement offer. Most adjusters
        will send the report within one to three business days. If your
        adjuster is unresponsive, escalate to a supervisor or contact your
        state&apos;s department of insurance.
      </p>

      {/* ---------------------------------------------------------------- */}
      {/*  Five Sections                                                     */}
      {/* ---------------------------------------------------------------- */}

      <h2 id="five-sections-of-a-valuation-report">
        The Five Key Sections of a Valuation Report
      </h2>

      <DataTable
        caption="Key sections of an insurance total loss valuation report and what to verify in each"
        headers={["Section", "What It Contains", "What to Verify"]}
        rows={[
          [
            "Vehicle Identification",
            "VIN, year, make, model, trim level, body style, engine",
            "Confirm the trim level is correct — base vs. mid vs. loaded trim can shift ACV by $2,000–$5,000",
          ],
          [
            "Mileage",
            "Your reported odometer reading",
            "Verify it matches your title, service records, and registration",
          ],
          [
            "Condition Rating",
            "Overall condition score and per-component ratings (interior, exterior, mechanical, tires)",
            "Dispute if rated lower than your documented condition; photos and service records are your evidence",
          ],
          [
            "Comparable Vehicles",
            "3–5 listings used to establish ACV (year, make, model, mileage, price, location)",
            "Check trim level, mileage, distance from your zip code, and whether options match",
          ],
          [
            "Adjustments",
            "Per-item additions or deductions applied to each comparable to normalize for differences",
            "Verify the direction (+ or –) and magnitude; mileage adjustments and condition adjustments are most often wrong",
          ],
          [
            "Final ACV",
            "Weighted average of the adjusted comparable values",
            "This is your starting negotiation point; verify it matches the arithmetic in the report",
          ],
        ]}
      />

      <h3 id="vehicle-identification">1. Vehicle Identification</h3>

      <p>
        The very first thing to check is whether the report correctly identifies
        your vehicle&apos;s trim level. Trim level is the most frequent source
        of systematic undervaluation in insurance reports. A base LE trim and
        a fully loaded Limited trim of the same model year can differ by $4,000
        to $8,000 in market value, but the insurer may have used your VIN to
        decode the trim and gotten it wrong &mdash; or deliberately selected
        lower-trim comparables.
      </p>

      <p>
        Pull your window sticker, original purchase agreement, or your
        vehicle&apos;s Carfax report to confirm every factory-installed option
        and trim designation. If the report lists your vehicle as a base model
        and you had a premium trim, that single error may be responsible for a
        significant share of your underpayment.
      </p>

      <h3 id="condition-rating">2. Condition Rating</h3>

      <p>
        CCC and similar platforms rate vehicle condition on a scale:
        Excellent, Good, Average, Rough, and Very Rough. Each step down
        in condition reduces ACV. If your vehicle was well-maintained, had
        current service records, and showed no significant interior or
        exterior wear, a rating below &quot;Good&quot; is worth disputing.
      </p>

      <p>
        Your evidence for a condition dispute includes pre-loss photographs,
        maintenance records, recent oil change receipts, and an independent
        appraisal from a licensed vehicle appraiser. Even a bump from
        &quot;Average&quot; to &quot;Good&quot; condition can meaningfully
        increase your ACV on a vehicle worth $15,000 or more.
      </p>

      <h3 id="comparable-vehicles">3. Comparable Vehicles</h3>

      <p>
        The comparable vehicles section is where most valuation errors live.
        Each comparable should match your vehicle on four key dimensions:
        trim level, model year, approximate mileage, and geographic proximity.
        When comparables deviate on any of these dimensions without a
        corresponding adjustment, your ACV is likely skewed downward.
      </p>

      <p>
        Read each comparable listing carefully. Note the trim designation,
        mileage, price, and the city where it is listed. Then search for the
        same vehicle on Cars.com, AutoTrader, and CarGurus to see if the
        listing price is current and accurate. Valuation platforms sometimes
        pull outdated listings or listings that have already been adjusted
        down after sitting on the lot.
      </p>

      <h3 id="adjustments">4. Adjustments</h3>

      <p>
        Each comparable is adjusted to account for differences between that
        vehicle and yours. Common adjustment types include mileage, condition,
        equipment, and trim. The adjustment math should be transparent in the
        report: you should be able to see what adjustment was applied to each
        comparable and in which direction.
      </p>

      <p>
        Pay close attention to the mileage adjustment. If your vehicle had
        significantly lower mileage than the comparables, there should be
        a positive (upward) adjustment to your ACV to reflect the value of
        lower miles. If that adjustment is missing or smaller than expected,
        your ACV is understated. A common benchmark is $0.05 to $0.15 per
        mile of difference, depending on vehicle age and class.
      </p>

      <h3 id="final-acv">5. Final ACV</h3>

      <p>
        The final ACV is typically a weighted average of the adjusted
        comparable values. Some platforms weight more recent listings or
        closer comparables more heavily. Verify that the arithmetic is correct
        by working through the comparables yourself. Then compare the final
        ACV to current market listings for your specific vehicle (same trim,
        similar mileage, local to your zip code).
      </p>

      {/* ---------------------------------------------------------------- */}
      {/*  Red Flags                                                        */}
      {/* ---------------------------------------------------------------- */}

      <h2 id="red-flags-in-comparables">Red Flags in the Comparable Vehicles</h2>

      <h3 id="common-comparable-errors">Common Comparable Selection Errors</h3>

      <DataTable
        caption="Common errors in comparable vehicle selection and how to dispute them"
        headers={["Error Type", "Example", "Impact on ACV", "How to Dispute"]}
        rows={[
          [
            "Wrong trim level",
            "Base LE used as comparable for your EX-L",
            "ACV artificially reduced by thousands",
            "Find same-trim comparables; cite Edmunds or KBB trim-specific pricing",
          ],
          [
            "Geographic mismatch",
            "Comparables from 150+ miles away in a lower-priced market",
            "ACV pulled down by out-of-market pricing",
            "Provide comparables within 25–50 miles; reference local dealer listings",
          ],
          [
            "Excessive mileage on comparables",
            "Comparables average 40,000 more miles than your vehicle",
            "Insufficient upward adjustment to your ACV",
            "Calculate per-mile value using NADA or KBB; request correction",
          ],
          [
            "Missing factory options",
            "Sunroof, AWD, leather seats not reflected",
            "Option value excluded from ACV",
            "Provide original window sticker; cite option values from KBB or dealer",
          ],
          [
            "Outdated listings",
            "Comparable pulled from a listing that has since sold or was price-reduced",
            "Stale pricing lowers ACV",
            "Verify listing is current; replace with active comparable listings",
          ],
          [
            "Condition rating too low",
            "Vehicle rated 'Average' despite excellent maintenance records",
            "ACV reduced by condition discount",
            "Submit maintenance records, pre-loss photos, and request re-rating",
          ],
        ]}
      />

      {/* ---------------------------------------------------------------- */}
      {/*  How to Dispute                                                   */}
      {/* ---------------------------------------------------------------- */}

      <h2 id="how-to-dispute-the-report">How to Dispute the Valuation Report</h2>

      <p>
        Once you have identified specific errors in the report, the dispute
        process is straightforward. You are not filing a formal appeal; you
        are providing your adjuster with evidence that specific line items in
        the report are inaccurate and requesting a correction.
      </p>

      <p>
        <strong>Step 1: Build your own comparable set.</strong> Search
        Cars.com, AutoTrader, CarGurus, and local dealer sites for your exact
        trim level within 50 miles of your zip code. Aim for five to seven
        listings with similar mileage. Screenshot each listing with the price,
        mileage, trim, and dealer name visible.
      </p>

      <p>
        <strong>Step 2: Document every error you found.</strong> For each
        error in the report, note the specific comparable number, the nature
        of the error (wrong trim, geographic mismatch, etc.), the dollar
        impact you believe it has on your ACV, and your supporting evidence.
      </p>

      <p>
        <strong>Step 3: Calculate a revised ACV.</strong> Use your corrected
        comparables and adjustments to calculate what you believe the ACV
        should be. This becomes the basis for your{" "}
        <Link href="/guides/counter-offer-letter" className="text-coral hover:underline">
          counter-offer letter
        </Link>
        .
      </p>

      <p>
        <strong>Step 4: Submit in writing.</strong> Send your dispute to your
        adjuster by email. Reference specific comparable numbers from the
        report. Attach your supporting comparables and any documentation
        (window sticker, maintenance records, photos). Request a written
        response to each point.
      </p>

      <p>
        <strong>Step 5: Escalate if needed.</strong> If your adjuster rejects
        your dispute without a substantive written explanation for each item,
        you can escalate to a supervisor, invoke the{" "}
        <Link href="/guides/appraisal-clause-insurance" className="text-coral hover:underline">
          appraisal clause
        </Link>{" "}
        in your policy for an independent binding valuation, or file a
        complaint with your state&apos;s department of insurance.
      </p>

      <h3 id="check-your-own-value">Check Your Own Vehicle&apos;s Value</h3>

      <p>
        Before sending your dispute, use our free car value estimator to get
        an independent ACV benchmark for your vehicle. Enter your year, make,
        model, mileage, and state to see an estimated fair market value range:
      </p>

      <CarValueEstimator mode="mini" />

      <CTABox
        heading="Get a line-by-line review of your valuation report"
        body="Upload your offer and valuation report. ClaimCoach identifies every comparable error, missing adjustment, and line-item gap — and generates a counter-offer with supporting evidence."
        href="/claims/new"
        label="Analyze my report"
      />

      {/* ---------------------------------------------------------------- */}
      {/*  Bottom Line                                                      */}
      {/* ---------------------------------------------------------------- */}

      <h2 id="the-bottom-line">The Bottom Line</h2>

      <KeyTakeaway>
        <p>
          Your insurer&apos;s settlement offer is only as accurate as the
          valuation report it came from. Request the report, read every
          comparable, verify the trim level and condition rating, and check
          each adjustment for accuracy and direction. When you find errors
          &mdash; and you often will &mdash; document them specifically and
          respond with corrected comparables. The report is the foundation
          of your settlement, and it is negotiable.
        </p>
      </KeyTakeaway>

      {/* ---------------------------------------------------------------- */}
      {/*  Related Guides                                                   */}
      {/* ---------------------------------------------------------------- */}

      <h2 id="related-guides" className="text-heading font-semibold text-black mt-10 mb-4">
        Related Guides
      </h2>

      <ul className="list-disc list-inside space-y-2 text-body text-[#4a555e] mb-6">
        <li>
          <Link href="/guides/total-loss-car-value" className="text-coral hover:underline">
            How Insurers Value Your Car
          </Link>{" "}
          &mdash; ACV methodology, depreciation, and comparable selection
        </li>
        <li>
          <Link href="/guides/counter-offer-letter" className="text-coral hover:underline">
            Counter-Offer Letter Template
          </Link>{" "}
          &mdash; how to present your corrected valuation in writing
        </li>
        <li>
          <Link href="/guides/appraisal-clause-insurance" className="text-coral hover:underline">
            How to Use the Appraisal Clause
          </Link>{" "}
          &mdash; when negotiation fails, request a binding independent appraisal
        </li>
        <li>
          <Link href="/guides/insurance-lowball-offer" className="text-coral hover:underline">
            Insurance Company Lowball Offer: What to Do Next
          </Link>{" "}
          &mdash; 7 warning signs your offer is below market
        </li>
      </ul>

      <div className="border-t border-black/10 mt-10 pt-6">
        <p className="text-caption text-[#4a555e]">
          <strong>Disclaimer:</strong> This article is for informational and
          educational purposes only and does not constitute legal, financial,
          or insurance advice. Valuation methodologies, platform features, and
          state regulations vary and are subject to change. Consult a licensed
          professional in your state for advice specific to your situation.
          Nothing in this article should be interpreted as a promise or
          prediction of any particular outcome.
        </p>
      </div>
    </>
  );
}
